language: en

pipeline:
   - name: SpacyNLP
     case_sensitive: false
     model: en_core_web_md
   - name: SpacyTokenizer
     token_pattern: "(\\d+|\\D+)"
   - name: SpacyFeaturizer
   - name: CountVectorsFeaturizer
   - name: DIETClassifier
     epochs: 10
     constrain_similarities: true


policies:
  - name: RulePolicy
