on:
  pull_request: {}

env:
  COMMIT_USERNAME: 'Github Actions'
  COMMIT_EMAIL: 'github.actions@users.noreply.github.com'
  DATA_DIRECTORY: 'data'
  TARGET_FILE_CONFIG: 'nlu_target_file_config.yml'
  COMMIT_MESSAGE: 'Github action: enforced NLU target files'

jobs:
  enforce_nlu_target_files:
    runs-on: ubuntu-latest
    name: Target Files
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}
    - name: Checkout pull request HEAD commit instead of merge commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Enforce NLU Target Files
      uses: RasaHQ/rasa-nlu-target-files-gha@v1.0.0
      with:
        nlu_target_file_config: ${{ env.TARGET_FILE_CONFIG }}
        update_config_file: true
    - name: Check if changes were made
      id: git_diff
      run: |
        git diff --exit-code
      continue-on-error: true
    - name: Commit changes if any were made
      if: steps.git_diff.outcome=='failure'
      run: |
        git config --global user.name '${{ env.COMMIT_USERNAME }}'
        git config --global user.email '${{ env.COMMIT_EMAIL }}'
        git add '${{ env.DATA_DIRECTORY }}' '${{ env.TARGET_FILE_CONFIG }}'
        git commit -am '${{ env.COMMIT_MESSAGE }}'
        git push
