on:
  push:
    paths:
      - 'data/*'
      - 'project_structure.py'
      - 'project_structure.yml'
      - '.github/workflows/enforce_project_structure.yml'

  workflow_dispatch:
    inputs:
      apply_to_branch:
        description: 'Branch to enforce project structure on'
        required: true
        default: ''

jobs:
  enforce_project_structure:
    runs-on: ubuntu-latest
    name: Enforce Project Structure
    env:
      PROJECT_STRUCTURE_SCRIPT: project_structure.py
      PROJECT_STRUCTURE_FILE: project_structure.yml
    steps:
    - name: Set env vars
      if: github.event.inputs.apply_to_branch
      run: |
          echo "PROJECT_STRUCTURE_SCRIPT=${GITHUB_REF##*/}-$PROJECT_STRUCTURE_SCRIPT" >> $GITHUB_ENV
          echo "PROJECT_STRUCTURE_FILE=${GITHUB_REF##*/}-PROJECT_STRUCTURE_FILE" >> $GITHUB_ENV
    - name: Checkout default
      if: github.event.inputs.apply_to_branch==''
      uses: actions/checkout@v2
    - name: Checkout whole repo for access to other branches
      if: github.event.inputs.apply_to_branch
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install -r requirements-project-structure.txt
    - name: Copy project structure definition & script
      if: github.event.inputs.apply_to_branch
      run: |
        cp project_structure.py ${{ steps.vars.outputs.script }}
        cp project_structure.yml ${{ steps.vars.outputs.project_structure }}
    - name: Checkout branch to enforce structure on
      if: github.event.inputs.apply_to_branch
      run: |
        git checkout ${{ github.event.inputs.apply_to_branch}}
    - name: Enforce structure on branch
      run: |
        python $PROJECT_STRUCTURE_SCRIPT -enforce --project_structure_file $PROJECT_STRUCTURE_FILE
    - name: Check if changes were made
      id: git_diff
      run: |
        git diff --exit-code
      continue-on-error: true
    - name: Commit changes if any were made
      if: steps.git_diff.outcome=='failure'
      run: |
        git config --global user.name 'Github Actions'
        git config --global user.email 'github.actions@users.noreply.github.com'
        git commit -am "Github action: enforced project structure"
        git push
