on:
  push:
    paths:
      - 'data/*'
      - 'project_structure.py'
      - 'project_structure.yml'
      - '.github/workflows/enforce_project_structure.yml'
  workflow_dispatch:
    inputs:
      apply_to_branch:
        description: 'Branch to enforce project structure on'
        required: true
        default: ''

jobs:
  enforce_project_structure:
    runs-on: ubuntu-latest
    name: Enforce Project Structure
    steps:
    - name: Set target branches
      id: vars
      run: |
        echo ::set-output name=script::"${GITHUB_REF##*/}_project_structure.py"
        echo ::set-output name=project_structure::"${GITHUB_REF##*/}_project_structure.yml"
    - name: Checkout branch for project structure definition & script 
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install -r requirements-project-structure.txt
    - name: Copy project structure definition & script
      run: |
        cp project_structure.py ${{ steps.vars.outputs.script }}
        cp project_structure.yml ${{ steps.vars.outputs.project_structure }}
        echo $(ls)
    - name: Checkout branch to enforce structure on
      if: github.event.inputs.apply_to_branch
      run: |
        git checkout ${{ github.event.inputs.apply_to_branch}}
    - name: Enforce structure on branch
      run: |
        python ${{ steps.vars.outputs.script }} -enforce --project_structure_file ${{ steps.vars.outputs.project_structure }}
    - name: Check if changes were made
      id: git_diff
      run: |
        git diff --exit-code
      continue-on-error: true
    - name: Commit changes if any were made
      if: steps.git_diff.outcome=='failure'
      run: |
        git config --global user.name 'Github Actions'
        git config --global user.email 'github.actions@users.noreply.github.com'
        git add data/*
        git commit -am "Github action: enforced project structure"
        git push
